# Generated by Django 5.2.5 on 2025-09-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
