# Generated by Django 5.2.5 on 2025-09-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
