# Generated by Django 5.2.5 on 2025-08-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_community_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
