# Generated by Django 5.2.5 on 2025-09-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
